/* Generated by AN DISI Unibo */ 
package it.unibo.ioport

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Ioport ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "idle"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name� = actor.withobj.method�ENDIF
		val status = utils.cargoservice.IOPortStatus()
		 val wsAdapter = utils.cargoservice.IOPortWsAdapter(this, 7070)  
		return { //this:ActionBasciFsm
				state("idle") { //this:State
					action { //it:State
						CommUtils.outcyan("$name | idle, in attesa della pressione del pulsante...")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t02",targetState="onButtonPressed",cond=whenDispatch("pushButton"))
					transition(edgeName="t03",targetState="onSetOccupied",cond=whenDispatch("setOccupied"))
					transition(edgeName="t04",targetState="onBlinkLed",cond=whenDispatch("blinkLed"))
				}	 
				state("onButtonPressed") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("pushButton(NONE)"), Term.createTerm("pushButton(X)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								CommUtils.outcyan("$name | pulsante premuto, invio richiesta di carico")
								 var Occ = status.isOccupied()  
								request("loadrequest", "loadrequest($Occ)" ,"cargoservice" )  
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t15",targetState="showAccepted",cond=whenReply("loadaccepted"))
					transition(edgeName="t16",targetState="showRejected",cond=whenReply("loadrejected"))
					transition(edgeName="t17",targetState="onBlinkLed",cond=whenDispatch("blinkLed"))
				}	 
				state("showAccepted") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("loadaccepted(SLOT,HOLD)"), Term.createTerm("loadaccepted(SLOT,HOLD)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 var S = payloadArg(0)  
								 var H = payloadArg(1)  
								CommUtils.outcyan("$name | display -> richiesta accettata, slot=$S")
								 wsAdapter.updateDisplay("ENGAGED", H, "Richiesta accettata - slot " + S)  
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="idle", cond=doswitch() )
				}	 
				state("showRejected") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("loadrejected(REASON,HOLD)"), Term.createTerm("loadrejected(REASON,HOLD)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 var R = payloadArg(0)  
								 var H = payloadArg(1)  
								CommUtils.outcyan("$name | display -> richiesta rifiutata, reason=$R")
								 wsAdapter.updateDisplay("IDLE", H, "Richiesta rifiutata: " + R)  
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="idle", cond=doswitch() )
				}	 
				state("onSetOccupied") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("setOccupied(FLAG)"), Term.createTerm("setOccupied(FLAG)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 var F = payloadArg(0)  
								 status.setOccupied(F.toBoolean())  
								CommUtils.outcyan("$name | sensore IOPort forzato a occupied=$F")
								 wsAdapter.notifySensor(F)  
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="idle", cond=doswitch() )
				}	 
				state("onBlinkLed") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("blinkLed(STATE,HOLD)"), Term.createTerm("blinkLed(STATE,HOLD)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 var S = payloadArg(0)  
								 var H = payloadArg(1)  
								CommUtils.outcyan("$name | led -> $S")
								 wsAdapter.setLed(S)  
								if(  S == "off"  
								 ){ wsAdapter.updateDisplay("IDLE", H, "Timeout scaduto: slot liberato, torno idle")  
								}
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="idle", cond=doswitch() )
				}	 
			}
		}
} 
