/* Generated by AN DISI Unibo */ 
package it.unibo.cargoservicecaller

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Cargoservicecaller ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name� = actor.withobj.method�ENDIF
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						request("loadrequest", "loadrequest(false)" ,"cargoservice" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t08",targetState="handleAccepted",cond=whenReply("loadaccepted"))
					transition(edgeName="t09",targetState="handleRejected",cond=whenReply("loadrejected"))
				}	 
				state("handleAccepted") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("loadaccepted(SLOT,HOLD)"), Term.createTerm("loadaccepted(SLOT,HOLD)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 var S = payloadArg(0)  
								CommUtils.outmagenta("$name | richiesta accettata, slot=$S")
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
				}	 
				state("handleRejected") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("loadrejected(REASON,HOLD)"), Term.createTerm("loadrejected(REASON,HOLD)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 var R = payloadArg(0)  
								CommUtils.outmagenta("$name | richiesta rifiutata, reason=$R")
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
				}	 
			}
		}
} 
