/* Generated by AN DISI Unibo */ 
package it.unibo.cargorobot

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Cargorobot ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "idle"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name� = actor.withobj.method�ENDIF
		 var TargetSlot = -1
		       val SLOT5_X = 2      // TODO: sostituire con le coordinate reali di slot5
		       val SLOT5_Y = 5
		       val HOME_X  = 0      // TODO: sostituire con le coordinate reali di HOME
		       val HOME_Y  = 0
		       fun slotX(s:Int) = when(s) { 1->1; 2->1; 3->3; 4->3; else->0 }   // TODO: mappatura placeholder, da sostituire
		       fun slotY(s:Int) = when(s) { 1->1; 2->3; 3->1; 4->3; else->0 }   // con il layout reale degli slot
		return { //this:ActionBasciFsm
				state("idle") { //this:State
					action { //it:State
						CommUtils.outyellow("$name | idle, in attesa di un incarico di trasporto...")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t02",targetState="startTransport",cond=whenRequest("transportContainer"))
				}	 
				state("startTransport") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("transportContainer(SLOT)"), Term.createTerm("transportContainer(SLOT)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 TargetSlot = payloadArg(0).toInt()  
								CommUtils.outyellow("$name | incarico ricevuto (slot riservato=$TargetSlot), vado a slot5")
								request("moverobot", "moverobot($SLOT5_X,$SLOT5_Y,345)" ,"robotsmart" )  
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t13",targetState="atSlot5",cond=whenReply("moverobotdone"))
					transition(edgeName="t14",targetState="halted",cond=whenReply("moverobotfailed"))
				}	 
				state("atSlot5") { //this:State
					action { //it:State
						CommUtils.outyellow("$name | container depositato in slot5, attendo fine marcatura")
						request("waitMarking", "waitMarking(NONE)" ,"cargoservice" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t25",targetState="goToReservedSlot",cond=whenReply("markingDone"))
				}	 
				state("goToReservedSlot") { //this:State
					action { //it:State
						CommUtils.outyellow("$name | marcatura completata, vado allo slot riservato $TargetSlot")
						request("moverobot", "moverobot(slotX($TargetSlot),slotY($TargetSlot),345)" ,"robotsmart" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t36",targetState="goHome",cond=whenReply("moverobotdone"))
					transition(edgeName="t37",targetState="halted",cond=whenReply("moverobotfailed"))
				}	 
				state("goHome") { //this:State
					action { //it:State
						CommUtils.outyellow("$name | container depositato, torno in HOME")
						request("moverobot", "moverobot($HOME_X,$HOME_Y,345)" ,"robotsmart" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t48",targetState="done",cond=whenReply("moverobotdone"))
					transition(edgeName="t49",targetState="halted",cond=whenReply("moverobotfailed"))
				}	 
				state("done") { //this:State
					action { //it:State
						CommUtils.outyellow("$name | HOME raggiunta, trasporto completato")
						answer("transportContainer", "transportDone", "transportDone($TargetSlot)"   )  
						 TargetSlot = -1  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="idle", cond=doswitch() )
				}	 
				state("halted") { //this:State
					action { //it:State
						CommUtils.outred("$name | guasto RobotSmart26 rilevato, mi fermo e attendo decisione")
						forward("robotHalted", "robotHalted(guastoRobotSmart26)" ,"cargoservice" ) 
						answer("transportContainer", "transportFailed", "transportFailed(guastoRobotSmart26)"   )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
				}	 
			}
		}
} 
