/* Generated by AN DISI Unibo */ 
package it.unibo.cargorobot

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Cargorobot ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "idle"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name� = actor.withobj.method�ENDIF
		val hold = utils.cargoservice.Hold()
		 var TargetSlot = -1
		       var TargetX = -1
		       var TargetY = -1
		return { //this:ActionBasciFsm
				state("idle") { //this:State
					action { //it:State
						CommUtils.outyellow("$name | idle, in attesa di un incarico di trasporto...")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t05",targetState="startTransport",cond=whenRequest("transportContainer"))
				}	 
				state("startTransport") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("transportContainer(SLOT,TARGETX,TARGETY)"), Term.createTerm("transportContainer(SLOT,TARGETX,TARGETY)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 TargetSlot = payloadArg(0).toInt()
								               TargetX = payloadArg(1).toInt()
								               TargetY = payloadArg(2).toInt()
								               var IOPort = hold.getIOPortPosition()
								               var X_IOPort =  IOPort.getX()
								               var Y_IOPort = IOPort.getY()
								CommUtils.outyellow("$name | incarico ricevuto (slot riservato=$TargetSlot, x=$TargetX,y=$TargetY), vado all'IOPort per il ritiro del container")
								request("moverobot", "moverobot($X_IOPort,$Y_IOPort,345)" ,"robotsmart" )  
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t16",targetState="atIOPort",cond=whenReply("moverobotdone"))
					transition(edgeName="t17",targetState="halted",cond=whenReply("moverobotfailed"))
				}	 
				state("atIOPort") { //this:State
					action { //it:State
						CommUtils.outyellow("$name | arrivato in IoPort")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
				 	 		stateTimer = TimerActor("timer_atIOPort", 
				 	 					  scope, context!!, "local_tout_"+name+"_atIOPort", 2000.toLong() )  //OCT2023
					}	 	 
					 transition(edgeName="t28",targetState="goToSlot5",cond=whenTimeout("local_tout_"+name+"_atIOPort"))   
				}	 
				state("goToSlot5") { //this:State
					action { //it:State
						 var S5 = hold.getSlot5Position()
						               var X_S5 =  S5.getX()
						               var Y_S5 = S5.getY()  
						CommUtils.outyellow("$name | container ritirato, vado allo slot5 per la marcatura")
						request("moverobot", "moverobot($X_S5,$Y_S5,345)" ,"robotsmart" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t39",targetState="atSlot5",cond=whenReply("moverobotdone"))
					transition(edgeName="t310",targetState="halted",cond=whenReply("moverobotfailed"))
				}	 
				state("atSlot5") { //this:State
					action { //it:State
						CommUtils.outyellow("$name | container depositato in slot5, attendo fine marcatura")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
				 	 		stateTimer = TimerActor("timer_atSlot5", 
				 	 					  scope, context!!, "local_tout_"+name+"_atSlot5", 2000.toLong() )  //OCT2023
					}	 	 
					 transition(edgeName="t411",targetState="goToReservedSlot",cond=whenTimeout("local_tout_"+name+"_atSlot5"))   
				}	 
				state("goToReservedSlot") { //this:State
					action { //it:State
						CommUtils.outyellow("$name | marcatura completata, vado allo slot riservato $TargetSlot")
						request("moverobot", "moverobot($TargetX,$TargetY,345)" ,"robotsmart" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t512",targetState="atSlot",cond=whenReply("moverobotdone"))
					transition(edgeName="t513",targetState="halted",cond=whenReply("moverobotfailed"))
				}	 
				state("atSlot") { //this:State
					action { //it:State
						CommUtils.outyellow("$name | arrivato allo slot riservato $TargetSlot")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
				 	 		stateTimer = TimerActor("timer_atSlot", 
				 	 					  scope, context!!, "local_tout_"+name+"_atSlot", 2000.toLong() )  //OCT2023
					}	 	 
					 transition(edgeName="t614",targetState="goHome",cond=whenTimeout("local_tout_"+name+"_atSlot"))   
				}	 
				state("goHome") { //this:State
					action { //it:State
						 var H = hold.getHomePosition()
						        	var X_HOME = H.getX()
						            var Y_HOME = H.getY()
						CommUtils.outyellow("$name | container depositato, torno in HOME")
						request("moverobot", "moverobot($X_HOME,$Y_HOME,345)" ,"robotsmart" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t715",targetState="done",cond=whenReply("moverobotdone"))
					transition(edgeName="t716",targetState="halted",cond=whenReply("moverobotfailed"))
				}	 
				state("done") { //this:State
					action { //it:State
						CommUtils.outyellow("$name | HOME raggiunta, trasporto completato")
						answer("transportContainer", "transportDone", "transportDone($TargetSlot)"   )  
						 TargetSlot = -1
						           TargetX = -1
						           TargetY = -1  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="idle", cond=doswitch() )
				}	 
				state("halted") { //this:State
					action { //it:State
						CommUtils.outred("$name | guasto RobotSmart26 rilevato, mi fermo e attendo decisione")
						forward("robotHalted", "robotHalted(guastoRobotSmart26)" ,"cargoservice" ) 
						answer("transportContainer", "transportFailed", "transportFailed(guastoRobotSmart26)"   )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
				}	 
			}
		}
} 
