/* Generated by AN DISI Unibo */ 
package it.unibo.cargoservice

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Cargoservice ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "idle"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name� = actor.withobj.method�ENDIF
		val hold = utils.cargoservice.Hold()
		 var Slot = -1
		     var Occupied = false  
		return { //this:ActionBasciFsm
				state("idle") { //this:State
					action { //it:State
						CommUtils.outmagenta("$name | idle, in attesa di richieste...")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t00",targetState="handleRequest",cond=whenRequest("loadrequest"))
				}	 
				state("handleRequest") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("loadrequest(OCCUPIED)"), Term.createTerm("loadrequest(X)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 Occupied = payloadArg(0).toBoolean()  
								 var H = "'" + hold.displayStatus() + "'"  
								if(  Occupied == true  
								 ){answer("loadrequest", "loadrejected", "loadrejected(retrylater,$H)"   )  
								}
								else
								 { Slot = hold.reserveFirstFree()  
								 if(  Slot != -1  
								  ){ var H2 = "'" + hold.displayStatus() + "'"  
								 forward("blinkLed", "blinkLed(on,$H2)" ,"ioport" ) 
								 answer("loadrequest", "loadaccepted", "loadaccepted($Slot,$H2)"   )  
								 }
								 else
								  {answer("loadrequest", "loadrejected", "loadrejected(full,$H)"   )  
								  }
								 }
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="engaged", cond=doswitchGuarded({ Slot != -1  
					}) )
					transition( edgeName="goto",targetState="idle", cond=doswitchGuarded({! ( Slot != -1  
					) }) )
				}	 
				state("engaged") { //this:State
					action { //it:State
						CommUtils.outmagenta("$name | engaged")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
				 	 		stateTimer = TimerActor("timer_engaged", 
				 	 					  scope, context!!, "local_tout_"+name+"_engaged", 30000.toLong() )  //OCT2023
					}	 	 
					 transition(edgeName="t11",targetState="disengaged",cond=whenTimeout("local_tout_"+name+"_engaged"))   
				}	 
				state("disengaged") { //this:State
					action { //it:State
						CommUtils.outmagenta("$name | timeout scaduto, libero lo slot e torno idle")
						 hold.releaseReserved()  
						 var H = "'" + hold.displayStatus() + "'"  
						forward("blinkLed", "blinkLed(off,$H)" ,"ioport" ) 
						 Slot = -1  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="idle", cond=doswitch() )
				}	 
			}
		}
} 
