/* Generated by AN DISI Unibo */ 
package it.unibo.cargoservice

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Cargoservice ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "idle"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name� = actor.withobj.method�ENDIF
		val hold = utils.cargoservice.Hold()
		 var Slot = -1
		     var Occupied = false
		     hold.setAllSlotsFree()  
		return { //this:ActionBasciFsm
				state("idle") { //this:State
					action { //it:State
						var Stato = hold.displayStatus().toString()  
						CommUtils.outmagenta("$Stato")
						CommUtils.outmagenta("$name | idle, in attesa di richieste...")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t00",targetState="handleRequest",cond=whenRequest("loadrequest"))
				}	 
				state("handleRequest") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("loadrequest(OCCUPIED)"), Term.createTerm("loadrequest(X)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 Occupied = payloadArg(0).toBoolean()  
								 var H = "'" + hold.displayStatus() + "'"  
								if(  Occupied == true  
								 ){answer("loadrequest", "loadrejected", "loadrejected(retrylater,$H)"   )  
								}
								else
								 { Slot = hold.reserveFirstFree()  
								 if(  Slot != -1  
								  ){ var H2 = "'" + hold.displayStatus() + "'"  
								 CommUtils.outmagenta("$name | richiesta accettata (hold=$H2)")
								 answer("loadrequest", "loadaccepted", "loadaccepted($Slot,$H2)"   )  
								 }
								 else
								  {answer("loadrequest", "loadrejected", "loadrejected(full,$H)"   )  
								  }
								 }
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="engaged", cond=doswitchGuarded({ Slot != -1 && Occupied == false  
					}) )
					transition( edgeName="goto",targetState="idle", cond=doswitchGuarded({! ( Slot != -1 && Occupied == false  
					) }) )
				}	 
				state("engaged") { //this:State
					action { //it:State
						 var TX = hold.slotX(Slot)
							       var TY = hold.slotY(Slot)  
						CommUtils.outmagenta("$name | engaged, incarico cargorobot per slot $Slot (x=$TX,y=$TY)")
						forward("blinkLed", "blinkLed(true)" ,"sonar" ) 
						request("transportContainer", "transportContainer($Slot,$TX,$TY)" ,"cargorobot" )  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="waitingTransport", cond=doswitch() )
				}	 
				state("waitingTransport") { //this:State
					action { //it:State
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
				 	 		stateTimer = TimerActor("timer_waitingTransport", 
				 	 					  scope, context!!, "local_tout_"+name+"_waitingTransport", 30000.toLong() )  //OCT2023
					}	 	 
					 transition(edgeName="t11",targetState="disengaged",cond=whenTimeout("local_tout_"+name+"_waitingTransport"))   
					transition(edgeName="t12",targetState="success",cond=whenReply("transportDone"))
					transition(edgeName="t13",targetState="disengaged",cond=whenReply("transportFailed"))
					transition(edgeName="t14",targetState="rejectBusy",cond=whenRequest("loadrequest"))
				}	 
				state("rejectBusy") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("loadrequest(OCCUPIED)"), Term.createTerm("loadrequest(X)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 var H = "'" + hold.displayStatus() + "'"  
								CommUtils.outmagenta("$name | sistema occupato, rifiuto nuova richiesta")
								answer("loadrequest", "loadrejected", "loadrejected(retrylater,$H)"   )  
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="waitingTransport", cond=doswitch() )
				}	 
				state("disengaged") { //this:State
					action { //it:State
						CommUtils.outmagenta("$name | timeout scaduto, libero lo slot e torno idle")
						 hold.releaseReserved()  
						 var H = "'" + hold.displayStatus() + "'"  
						 var S = "'IDLE'"  
						 var M = "'Timeout scaduto: slot liberato, torno idle'"  
						forward("blinkLed", "blinkLed(false)" ,"sonar" ) 
						forward("updateDisplay", "updateDisplay($S,$H,$M)" ,"ioport" ) 
						 Slot = -1  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="idle", cond=doswitch() )
				}	 
				state("success") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("transportDone(SLOT)"), Term.createTerm("transportDone(SLOT)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 Slot = payloadArg(0).toInt()
								            	var Done  = hold.setReservedSlotOccupied()
								CommUtils.outmagenta("$name | trasporto del container in slot $Slot terminato, torno idle")
								 hold.releaseReserved()  
								 var H = "'" + hold.displayStatus() + "'"  
								 var S = "'IDLE'"  
								 var M = "'Trasporto terminato'"  
								forward("blinkLed", "blinkLed(false)" ,"sonar" ) 
								forward("updateDisplay", "updateDisplay($S,$H,$M)" ,"ioport" ) 
								 Slot = -1  
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="idle", cond=doswitch() )
				}	 
			}
		}
} 
