/* Generated by AN DISI Unibo */ 
package it.unibo.sonar

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Sonar ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "idle"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name� = actor.withobj.method�ENDIF
		 var DFREE = 30              // cm — soglia provvisoria Sprint0, da calibrare (vedi TP-B1)
		       var Dist = 0.0
		       var Occupied = false
		       var Faulted = false
		       var T0Container = 0L        // 0 = nessuna finestra di conferma container in corso
		       var T0Fault = 0L            // 0 = nessuna finestra di conferma guasto in corso
		       var WINDOW = 3000L          // 3 secondi, requisito esplicito di Sprint0
		       var MqttLink = utils.cargoservice.SonarMqttAdapter(this,
		           "192.168.0.218", "cargoservice/sonar/distance", "cargoservice/sonar/led")
		return { //this:ActionBasciFsm
				state("idle") { //this:State
					action { //it:State
						CommUtils.outblue("$name | idle, in ascolto delle letture del PicoW via MQTT...")
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t030",targetState="onReading",cond=whenEvent("sonarreading"))
					transition(edgeName="t031",targetState="onBlink",cond=whenDispatch("blinkLed"))
				}	 
				state("onReading") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("sonarreading(DISTANCE)"), Term.createTerm("sonarreading(D)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 Dist = payloadArg(0).toDouble()
								               var Now = System.currentTimeMillis()
								if(  Dist < DFREE/2.0  
								 ){ if (T0Container == 0L) { T0Container = Now }  
								if(  !Occupied && (Now - T0Container) >= WINDOW  
								 ){ Occupied = true  
								CommUtils.outblue("$name | container rilevato (D=$Dist cm), notifico ioport")
								forward("setOccupied", "setOccupied(true)" ,"ioport" ) 
								}
								}
								else
								 { T0Container = 0L  
								 if(  Occupied && Dist >= DFREE/2.0  
								  ){ Occupied = false  
								 CommUtils.outblue("$name | container non piu' rilevato (D=$Dist cm)")
								 forward("setOccupied", "setOccupied(false)" ,"ioport" ) 
								 }
								 }
								if(  Dist > DFREE  
								 ){ if (T0Fault == 0L) { T0Fault = Now }  
								if(  !Faulted && (Now - T0Fault) >= WINDOW  
								 ){ Faulted = true  
								CommUtils.outred("$name | guasto sonar sospetto (D=$Dist cm)")
								forward("sonarfault", "sonarfault(sonarOutOfRange)" ,"cargoservice" ) 
								forward("sonarfault", "sonarfault(sonarOutOfRange)" ,"cargorobot" ) 
								}
								}
								else
								 { T0Fault = 0L  
								 if(  Faulted  
								  ){ Faulted = false  
								 CommUtils.outblue("$name | sonar ripristinato (D=$Dist cm)")
								 forward("sonarrestored", "sonarrestored(NONE)" ,"cargoservice" ) 
								 forward("sonarrestored", "sonarrestored(NONE)" ,"cargorobot" ) 
								 }
								 }
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="idle", cond=doswitch() )
				}	 
				state("onBlink") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("blinkLed(FLAG)"), Term.createTerm("blinkLed(FLAG)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 var F = payloadArg(0)  
								 MqttLink.sendLed(F.toBoolean())  
								CommUtils.outblue("$name | comando Led($F) inoltrato al PicoW via MQTT")
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="idle", cond=doswitch() )
				}	 
			}
		}
} 
